charity/config/routes.rb
Rails.application.routes.draw do
 
  post '/rate' => 'rater#create', :as => 'rate'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users ,:controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}
  devise_scope :user do
  get "/sign_in" => "home#login"
  get "/sign_up"   => "home#user_signup"
  get "/charity_signup"   => "home#charity_signup"
  get "/account_settings"   => "home#account_settings"
  end

  resources :mysquares
  resources :squares

  
  root 'home#index'
  match '/searching'    => 'home#searching', :via => [:get,:post]
  match '/bets/create' =>'bets#create' , :via =>[:get,:post]
  match '/appeals/create' =>'appeals#create' , :via =>[:get,:post]
  match '/pay' => 'home#pay', :via => [:get,:post]
  get '/search' => 'home#search'
  match '/charity'    => 'charityusersquares#charity', :via => [:get,:post]
  match '/charity/upload'    => 'charity_media#upload', :via => [:get,:post]
  resources :charitychildren

  match '/profile'    => 'home#profile', :via => [:get,:post]
  match '/profile_edit/:id'    => 'home#profile_edit', :via => [:get,:post]
  match '/edit_profile'    => 'home#edit_profile', :via => [:get,:post,:patch]

  get '/charity/remove/:id', to: 'charity_media#remove_picture', as: 'remove_picture'

  match '/charityusersquares/buynow/:id' => 'charityusersquares#buynow' ,as: 'charitybuy_path' ,:via =>[:get,:post]

  resources :charityusersquares
 
  match '/charity_squares'    => 'home#charity_squares', :via => [:get,:post]
  match '/buy_now'    => 'home#buy_now', :via => [:get,:post]
  match '/bets/:id/edit'    => 'bets#edit', :via => [:get,:post]
  match '/bets/:id'    => 'bets#show', as: 'bets_show', :via => [:get,:post]
  match '/update_bet' =>'bets#update' , :via => [:get,:post]
  match '/bets/remove/:id' => 'bets#delete', :via => [:get,:post]
  match '/appeal/:id/edit'    => 'appeals#edit', :via => [:get,:post]
  match '/appeal/:id'    => 'appeals#show', as: 'appeals_show', :via => [:get,:post]
  match '/update_appeal' =>'appeals#update' , :via => [:get,:post]
  match '/auctions'    => 'home#auctions', :via => [:get,:post]
  match '/appeals'    => 'home#appeals', :via => [:get,:post]
  match '/raffle_n_lottery'    => 'home#raffle_n_lottery', :via => [:get,:post]

  match '/view_transaction'    => 'home#view_transaction', :via => [:get,:post]

  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      delete :empty_trash
      post :mark_as_read
    end
  end

  resources :messages, only: [:new, :create]
  match '/home_page_feed'    => 'home#home_page_feed', :via => [:get,:post]
  match '/search_filter'    => 'home#search_filter', :via => [:get,:post]
  match '/filter'    => 'home#filter', :via => [:get,:post]

  match '/completed_payment_request'    => 'home#completed_payment_request', :via => [:get,:post]
  match '/ipn_notification'    => 'home#ipn_notification', :via => [:get,:post]
  match '/appeal_ipn'  => 'appeals#appeal_ipn', :via => [:get,:post]

  match '/my_square'    => 'home#my_square', :via => [:get,:post]
  
  match '/profile'    => 'home#profile', :via => [:get,:post]
  match '/follow'    => 'charityusersquares#follow', :via => [:get,:post]
  match '/follows'    => 'bets#follows', :via => [:get,:post]
  match '/order_summary'    => 'home#order_summary', :via => [:get,:post]
  match '/bet_response'    => 'bets#bet_response', :via => [:get,:post]
  match '/bet_removepic'    => 'bets#removepic', :via => [:get,:post]
  match '/appeal_donations' => 'appeals#appeal_donations', :via => [:get,:post]
  match '/appeal_removepic'    => 'appeals#removepic', :via => [:get,:post] 
  match '/bet_result/:id'    => 'bets#bet_result', as: 'bet_result', :via => [:get,:post]
  match '/bet_result1/:id'    => 'bets#bet_result1', as: 'bet_result1', :via => [:get,:post]
  match '/view_donations/:id'  => 'appeals#view_donations', as: 'view_donations', :via => [:get,:post]
  match '/purchase/result/:id'    => 'home#purchase_result', as: 'purchase_result', :via => [:get,:post]
  match '/invite'    => 'bets#invite', :via => [:get,:post]

  match '/approve'  => 'bets#approve', :via =>[:get,:post]
  match '/purchase' => 'home#manage_purchase', :via =>[:get,:post]

  match '/checkout'    => 'home#checkout', :via => [:get,:post]
  match '/order_confirmation'    => 'home#order_confirmation', :via => [:get,:post]
  match '/view_transaction'    => 'home#view_transaction', :via => [:get,:post]
  match '/select'    => 'home#select', :via => [:get,:post]
  match '/create_square'    => 'charityusersquares#create_square', :via => [:get,:post]
  match '/bet'    => 'charityusersquares#bet', :via => [:get,:post]
  match '/appeal'  => 'charityusersquares#appeal', :via => [:get,:post]

end

charity/app/views/layouts/_footer.html.erb
<div class="for_charity_and_help  left">
            <div class="row">
              <div class="large-12 columns">
                <ul class="left listing">
                  <li>
                    <a title="For charities" href="#">For charities</a>
                  </li>
                  <li>
                    <a title="For fundraisers" href="#">For fundraisers</a>
                  </li>
                  <li>
                    <a title="For supporters" href="#">For supporters</a>
                  </li>
                </ul>
                <ul class="right listing">
                  <li>
                    <a title="Help &amp; FAQ " href="#">Help &amp; FAQ </a>
                  </li>
                  <li>
                    <a title="About us" href="#">About us</a>
                  </li>
                  <li>
                    <a title="Create a square" href="#">Create a square</a>
                  </li>
                </ul>
              </div>  
            </div>  
          </div>
        </section>

        <div class="add_space left">
          <div class="row">
            <div class="large-12 columns">
              <div class="add_here text-center">
                <h1>ad space</h1>
              </div>
            </div>
          </div>
        </div>

        <footer class="footer_section left">
          <div class="row">
            <h1 class="text-center">Chari Squares Ltd &copy; 2015 All rights reserved</h1>
            <ul class="footer_nav_list left text-center">
              <li>
                <a title="Term &amp; Condisitons" href="#">Term &amp; Condisitons</a>
              </li>
              <li>
                <a title="Cokie policy" href="#">Cokie policy</a>
              </li>
              <li>
                <a title="Privacy Policy" href="#">Privacy Policy</a>
              </li>
            </ul>
            <h2 class="text-center">designed by awake<sup>&reg;</sup></h2>
          </div>
        </footer>

charity/app/views/layouts/_header.html.erb
        <nav data-topbar="" class="top-bar docs-bar hide-for-small">
          <%= render 'layouts/logo' %>
          <section class="top-bar-section text-center">
           <ul class="left">
              <li class="has-dropdown not-click">
                <a class="discov" href="#" title="discover">discover</a>             
              </li>
            </ul> 
            <div class="top_head_search">
              <div class="search_categories">
                 <%= form_tag filter_path, method: :post do %>
                    <%= text_field_tag :q, nil, :placeholder => 'search...' %>
                    <input type="submit" class="search" value=""></input>              
                        <select name='category' value='categories' >
                        <option selected='selected'>Categories</option>
                        <option>Lottery</option>
                        <option>Raffles</option>
                        <option>Auctions</option>
                        <option>Appeals</option>
                        <option>Bets</option>
                      </select>
                    <% end %>  
              </div>
            </div> 
            <ul class="right">
              <li class="has-dropdown not-click">
                <% if user_signed_in? %>
              <a href="javascript:void(0);" title="discover" style= "margin-top: -22px;"><a class="logedin" href="javascript:void(0);"><%= current_user.name %></a></a>
                  <ul class="dropdown">
                    <li class="parent-link hide-for-medium-up">
                      <a href="javascript:void(0);" title="discover1" class="test"><%= current_user.firstname %></a>
                    </li>

                    <!-- <li><a href='/home_page_feed'>Home page feed</a></li>
                    <li><a href="/profile" title="Demo">my profile</a></li>
                    <li><a href="/my_square" title="Demo">my squares</a></li>
                    <li><a href="#" title="Demo">manage purchases</a></li>
                    <li><a href="#" title="Demo">account settings</a></li>
                    <li><a href="/conversations" title="Demo">messages</a></li>
                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li> -->
                  </ul>
                   <li class="launch_square">
                      <a class="" href="/create_square" title="launch square">launch a square</a>
                   </li>
                <% else %>  
                 <li>
                  <a class="" href="/sign_up" title="Register">Register</a>
                 </li>
                 <li>
                  <a class="" href="/sign_in" title="Login">Login</a>
                 </li>
                 <li class="launch_square">
                  <a class="" href="/sign_in" title="launch square">launch a square</a>
                 </li>
                <% end %>  
              
              </li>   
            </ul>
          </section>
        </nav>

        <div class="descover_hover left">
          <div class="large-6 medium-6 small-12 columns">
            <ul class="descover_hover_filter left">
              <li class="all_descover_hover">
                <a href="#">All</a>
              </li>
              <li>
                <a href="#"></a>
              </li>
              <li>
                <a href="#"></a>
              </li>
              <li>
                <a href="#"></a>
              </li>
              <li>
                <a href="#"></a>
              </li>
              <li>
                <a href="#"></a>
              </li>
            </ul>
          </div>

          <div class="large-6 medium-6 small-6 columns">
            <div class="descover_right_text_show left">
              <h1>Appeals</h1>
              <p>Lorem ipsum dolor sit amet, consectetur<br> adipiscing elit. Cras egestas laoreet justo <br>et eleifend. </p>
            </div>
          </div>
          
        </div>

         <!--logedin_hover div -->
        <div class="logedin_hover left dropdown">
          <div class="large-12 medium-12 small-12 columns">
            <ul class="logedin_hover_sub_menu right">
              <li>
                <a href="#">about us</a>
              </li>
              <li>
                <a href="#">contact</a>
              </li>
              <li>
                <a href="#">help</a>
              </li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
            </ul>
            <ul class="logedin_hover_sub_menu my_profile_accounts right">
             <li>
            <a href='/home_page_feed'>Home page feed</a>
            </li>
              <li>
                <a href="#">child accounts</a>
              </li>
              <li>
                <a href="#">statistics</a>
              </li>
            </ul>
            <ul class="logedin_hover_sub_menu right">
           
              <li>
                <a href="/profile">my profile</a>
              </li>
              <li>
                <a href="/my_square">my squares</a>
              </li>
              <li>
                <a href="/purchase">manage purchases</a>
              </li>
              <li>
                <a href="/account_settings">accounts settings</a>
              </li>
              <li>
                 <a href="/conversations">messages <span class="logedin_message"></span></a> 
              </li>
            </ul>
          </div>
        </div>

         <%= render 'layouts/right_canvas' %>

        <a class="exit-off-canvas"></a>

        <!-- banner section start here -->
      

charity/app/views/layouts/_logo.html.erb
<ul class="title-area">
    <li class="name">
        <h1><a href="/" title="Logo">Logo</a></h1>
    </li>
</ul>

charity/app/views/layouts/_messages.html.haml
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

charity/app/views/layouts/_navigation.html.erb
        <nav data-topbar="" class="top-bar docs-bar hide-for-small">
          <%= render 'layouts/logo' %>
          <section class="top-bar-section">
            <ul class="left">
              <li class="has-dropdown not-click">
                <a class="discov" href="#" title="discover">discover</a>              
              </li>
            </ul>  
            <ul class="right">
            <li class="has-dropdown not-click">
              <% if user_signed_in? %>
              <a href="javascript:void(0);" title="discover" style= "margin-top: -22px;"><a class="logedin" href="javascript:void(0);"><%= current_user.name %></a></a>
                  <ul class="dropdown">
                    <li class="parent-link hide-for-medium-up">
                      <a href="javascript:void(0);" title="discover1" class="test"><%= link_to current_user.firstname %></a>
                    </li>

                    <!-- <li><a href='/home_page_feed'>Home page feed</a></li>
                    <li><a href="/profile" title="Demo">my profile</a></li>
                    <li><a href="/my_square" title="Demo">my squares</a></li>
                    <li><a href="#" title="Demo">manage purchases</a></li>
                    <li><a href="#" title="Demo">account settings</a></li>
                    <li><a href="/conversations" title="Demo">messages</a></li>
                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li> -->
                  </ul>
                   <li class="launch_square">
                      <a class="" href="/create_square" title="launch square">launch a square</a>
                   </li>
              <% else %>  
                <li>
                  <a class="" href="/sign_up" title="Register">Register</a>
                </li>
                <li>
                  <a class="" href="/sign_in" title="Login">Login</a>
                </li>
                <li class="launch_square">
                  <a class="" href="/sign_in" title="launch square">launch a square</a>
                </li>
              <% end %>  
              
             </li>   
            </ul>
          </section>
        </nav>

         <div class="descover_hover left">
          <div class="large-6 medium-6 small-12 columns">
            <ul class="descover_hover_filter left">
              <li class="all_descover_hover">
                <a href="#">All</a>
              </li>
              <li>
                <a href="#"></a>
              </li>
              <li>
                <a href="#"></a>
              </li>
              <li>
                <a href="#"></a>
              </li>
              <li>
                <a href="#"></a>
              </li>
              <li>
                <a href="#"></a>
              </li>
            </ul>
          </div>

          <div class="large-6 medium-6 small-6 columns">
            <div class="descover_right_text_show left">
              <h1>Appeals</h1>
              <p>Lorem ipsum dolor sit amet, consectetur<br> adipiscing elit. Cras egestas laoreet justo <br>et eleifend. </p>
            </div>
          </div>
          
        </div>

         <!--logedin_hover div -->
        <div class="logedin_hover left dropdown">
          <div class="large-12 medium-12 small-12 columns">
            <ul class="logedin_hover_sub_menu right">
              <li>
                <a href="#">about us</a>
              </li>
              <li>
                <a href="#">contact</a>
              </li>
              <li>
                <a href="#">help</a>
              </li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
            </ul>
            <ul class="logedin_hover_sub_menu my_profile_accounts right">
              <li>
            <a href='/home_page_feed'>Home page feed</a>
            </li>
              <li>
                <a href="#">child accounts</a>
              </li>
              <li>
                <a href="#">statistics</a>
              </li>
            </ul>
            <ul class="logedin_hover_sub_menu right">

              <li>
                <a href="/profile">my profile</a>
              </li>
              <li>
                <a href="/my_square">my squares</a>
              </li>
              <li>
                <a href="/purchase">manage purchases</a>
              </li>
              <li>
                <a href="/account_settings">accounts settings</a>
              </li>
              <li>
                 <a href="/conversations">messages <span class="logedin_message"></span></a> 
              </li>
            </ul>
          </div>
        </div>

 


        
        <%= render 'layouts/right_canvas' %>
        <a class="exit-off-canvas"></a>

charity/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

charity/app/views/layouts/_right_canvas.html.erb
      <nav class="tab-bar show-for-small">
          <section class="right-small">
            <a aria-expanded="false" class="right-off-canvas-toggle menu-icon"><span></span></a>
          </section>

          <section class="left tab-bar-section">
            <h1 class="title">
              <a class="left" href="#">Logo</a>
            </h1>
          </section>
        </nav>
        <aside class="right-off-canvas-menu">
          <ul class="off-canvas-list">
            <li><label>discover</label></li>
            <li><a href="#">Demo</a></li>
            <li><a href="#">Demo</a></li>
            <li><a href="#">Demo</a></li>
            <li><a href="#">Demo</a></li>
            <li><label>Register and Login</label></li>
            <% if user_signed_in? %>
              <li><%= link_to current_user.email %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
              <li><label>launch a square</label></li>
              <li><a href="/create_square">launch a square</a></li>
            <% else %>     
              <li><a href="/users/sign_up">Register</a></li>
              <li><a href="/home/login">Login</a></li>
              <li><label>launch a square</label></li>c
              <li><a href="/home/login">launch a square</a></li>
            <% end %>  
          </ul>
        </aside>

charity/app/views/layouts/application.html.erb
<html lang="en">
 <head>
   <meta charset="utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />

   <title><%= content_for?(:title) ? yield(:title) : "Charity Square" %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>

    <%= javascript_include_tag 'vendor/jquery' %>

    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'foundation.min.js' %>
    <%= javascript_include_tag "chosen-jquery" %> 
    <%= javascript_include_tag 'jquery.datetimepicker.js' %> 
    <%= javascript_include_tag 'jquery.raty.js' %> 
    <%= javascript_include_tag 'letsrate.js' %>
    <%= javascript_include_tag 'jquery.countdown.js' %>
    <%= javascript_include_tag 'tagmanager.js' %>
    <%= csrf_meta_tags %>
 
  </head>

  <body>
   <% if notice %>
    <div class="alert green_message">
      <div class="row">
        <div class="large-12 columns">
          <p class="left"><%= notice %></p>
          <a class="right" href="#" title="close message">
            <%= image_tag("close_message.png") %>
          </a>
        </div>
      </div>
    </div>
   <% end %>

   <% if alert %>
    <div class="alert red_message">
      <div class="row">
        <div class="large-12 columns">
          <p class="left"><%= alert %></p>
          <a class="right" href="#" title="close message">
            <%= image_tag("close_message.png", :class=>"close") %>
        </div>
      </div>
    </div>
   <% end %> 
  <!--  <div data-alert class="alert-box success radius">
      <div class="row">
        <div class="large-12 columns">
          <p class="left"><%#= alert %></p>
          <a href="#" class="close">&times;</a>
        </div>
      </div>
    </div> -->
  

    <%= yield %>

 </body>
</html>

<script type='text/javascript'>
  $('.alert').fadeOut(5000);
  $('.alert-box').fadeOut(5000);
  $(document).foundation();
</script>


<script>
  $(document).foundation();
  $('.discov').click(function(){
  $('.descover_hover').slideToggle()
  })
  $('.logedin').click(function(){
  $('.logedin_hover').slideToggle()
  })
</script>