charity/config/routes.rb
Rails.application.routes.draw do
 
  post '/rate' => 'rater#create', :as => 'rate'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users ,:controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}
  devise_scope :user do
  get "/sign_in" => "home#login"
  get "/sign_up"   => "home#user_signup"
  get "/charity_signup"   => "home#charity_signup"
  get "/account_settings"   => "home#account_settings"
  end

  resources :mysquares
  resources :squares

  
  root 'home#index'
  match '/searching'    => 'home#searching', :via => [:get,:post]
  match '/bets/create' =>'bets#create' , :via =>[:get,:post]
  match '/appeals/create' =>'appeals#create' , :via =>[:get,:post]
  match '/pay' => 'home#pay', :via => [:get,:post]
  get '/search' => 'home#search'
  match '/charity'    => 'charityusersquares#charity', :via => [:get,:post]
  match '/charity/upload'    => 'charity_media#upload', :via => [:get,:post]
  resources :charitychildren

  match '/profile'    => 'home#profile', :via => [:get,:post]
  match '/profile_edit/:id'    => 'home#profile_edit', :via => [:get,:post]
  match '/edit_profile'    => 'home#edit_profile', :via => [:get,:post,:patch]

  get '/charity/remove/:id', to: 'charity_media#remove_picture', as: 'remove_picture'

  match '/charityusersquares/buynow/:id' => 'charityusersquares#buynow' ,as: 'charitybuy_path' ,:via =>[:get,:post]

  resources :charityusersquares
 
  match '/charity_squares'    => 'home#charity_squares', :via => [:get,:post]
  match '/buy_now'    => 'home#buy_now', :via => [:get,:post]
  match '/bets/:id/edit'    => 'bets#edit', :via => [:get,:post]
  match '/bets/:id'    => 'bets#show', as: 'bets_show', :via => [:get,:post]
  match '/update_bet' =>'bets#update' , :via => [:get,:post]
  match '/bets/remove/:id' => 'bets#delete', :via => [:get,:post]
  match '/appeal/:id/edit'    => 'appeals#edit', :via => [:get,:post]
  match '/appeal/:id'    => 'appeals#show', as: 'appeals_show', :via => [:get,:post]
  match '/update_appeal' =>'appeals#update' , :via => [:get,:post]
  match '/auctions'    => 'home#auctions', :via => [:get,:post]
  match '/appeals'    => 'home#appeals', :via => [:get,:post]
  match '/raffle_n_lottery'    => 'home#raffle_n_lottery', :via => [:get,:post]

  match '/view_transaction'    => 'home#view_transaction', :via => [:get,:post]

  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      delete :empty_trash
      post :mark_as_read
    end
  end

  resources :messages, only: [:new, :create]
  match '/home_page_feed'    => 'home#home_page_feed', :via => [:get,:post]
  match '/search_filter'    => 'home#search_filter', :via => [:get,:post]
  match '/filter'    => 'home#filter', :via => [:get,:post]

  match '/completed_payment_request'    => 'home#completed_payment_request', :via => [:get,:post]
  match '/ipn_notification'    => 'home#ipn_notification', :via => [:get,:post]
  match '/appeal_ipn'  => 'appeals#appeal_ipn', :via => [:get,:post]

  match '/my_square'    => 'home#my_square', :via => [:get,:post]
  
  match '/profile'    => 'home#profile', :via => [:get,:post]
  match '/follow'    => 'charityusersquares#follow', :via => [:get,:post]
  match '/follows'    => 'bets#follows', :via => [:get,:post]
  match '/order_summary'    => 'home#order_summary', :via => [:get,:post]
  match '/bet_response'    => 'bets#bet_response', :via => [:get,:post]
  match '/bet_removepic'    => 'bets#removepic', :via => [:get,:post]
  match '/appeal_donations' => 'appeals#appeal_donations', :via => [:get,:post]
  match '/appeal_removepic'    => 'appeals#removepic', :via => [:get,:post] 
  match '/bet_result/:id'    => 'bets#bet_result', as: 'bet_result', :via => [:get,:post]
  match '/bet_result1/:id'    => 'bets#bet_result1', as: 'bet_result1', :via => [:get,:post]
  match '/view_donations/:id'  => 'appeals#view_donations', as: 'view_donations', :via => [:get,:post]
  match '/purchase/result/:id'    => 'home#purchase_result', as: 'purchase_result', :via => [:get,:post]
  match '/invite'    => 'bets#invite', :via => [:get,:post]

  match '/approve'  => 'bets#approve', :via =>[:get,:post]
  match '/purchase' => 'home#manage_purchase', :via =>[:get,:post]

  match '/checkout'    => 'home#checkout', :via => [:get,:post]
  match '/order_confirmation'    => 'home#order_confirmation', :via => [:get,:post]
  match '/view_transaction'    => 'home#view_transaction', :via => [:get,:post]
  match '/select'    => 'home#select', :via => [:get,:post]
  match '/create_square'    => 'charityusersquares#create_square', :via => [:get,:post]
  match '/bet'    => 'charityusersquares#bet', :via => [:get,:post]
  match '/appeal'  => 'charityusersquares#appeal', :via => [:get,:post]

end

charity/app/controllers/charitychildren_controller.rb
class CharitychildrenController < ApplicationController
  before_action :set_charitychild, only: [:show, :edit, :update, :destroy]
  # load_and_authorize_resource except: [:create]
  respond_to :html

  def index
    if current_user != nil
      @charitychildren = current_user.charitychildren  
      respond_with(@charitychildren)
    end  
  end

  def show
    respond_with(@charitychild)
  end

  def new
    @charitychild = Charitychild.new
    respond_with(@charitychild)
  end

  def edit
  end

  def create
    @charitychild = current_user.charitychildren.new(charitychild_params)
    @charitychild.save
    respond_with(@charitychild)
  end

  def update
    #render :plain =>mysquare_params
    @charitychild.update(charitychild_params)
    respond_with(@charitychild)
 
  end

  def destroy
    @charitychild.destroy
    respond_with(@charitychild)
  end

  private
    def set_charitychild
      @charitychild = Charitychild.find(params[:id])
    end

    def charitychild_params
      params.require(:charitychild).permit(:name, :email, :address, :active, :user_id)
    end
end

charity/app/helpers/charitychildren_helper.rb
module CharitychildrenHelper
end

charity/app/views/charitychildren/_form.html.erb
<%= form_for(@charitychild) do |f| %>
  <% if @charitychild.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charitychild.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% @charitychild.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">

    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

charity/app/views/charitychildren/edit.html.erb
<h1>Editing charity children</h1>

<%= render 'form' %>

<%= link_to 'Show', @charitychild %> |
<%= link_to 'Back', charitychildren_path %>

charity/app/views/charitychildren/index.html.erb
<h1>Listing charitychildren</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>Active</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% unless @charitychildren.nil? %>
    <% @charitychildren.each do |charitychildren| %>
      <tr>
        <td><%= charitychildren.name %></td>
        <td><%= charitychildren.email %></td>
        <td><%= charitychildren.address %></td>
        <td><%= charitychildren.active %></td>
        <td><%= User.find(charitychildren.user_id).email %></td>
        <td><%= link_to 'Show', charitychildren %></td>
        <td><%= link_to 'Edit', edit_charitychild_path(charitychildren) %></td>
        <td><%= link_to 'Destroy', charitychildren, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%end%>
  </tbody>
</table>

<br>

<%= link_to 'New Charitychild', new_charitychild_path %>

charity/app/views/charitychildren/new.html.erb
<h1>New charitychild</h1>

<%= render 'form' %>

<%= link_to 'Back', charitychildren_path %>

charity/app/views/charitychildren/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @charitychild.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @charitychild.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @charitychild.address %>
</p>

<p>
  <strong>Active:</strong>
  <%= @charitychild.active %>
</p>

<%= link_to 'Edit', edit_charitychild_path(@charitychild) %> |
<%= link_to 'Back', charitychildren_path %>